<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */

/**
 * Product video template
 *
 * @see Mage_Catalog_Block_Product_View_Description
 */
?>
<?php 
	$_product = $this->getProduct();
	$_helper = $this->helper('catalog/output');
?>
<div>TEST</div>
<?php if($_product->getData('product_video')): ?>
	<p data-magellan-destination="product-video"><a id="product-video"></a></p>
	<h3>PRODUCT VIDEOS</h3>
	<iframe width="560" height="315" src="http://www.youtube.com/embed/<?php echo $_product->getData('product_video') ?>" frameborder="0" allowfullscreen></iframe>
<?php endif; ?>