<div class="page-title">
    <h3><?php echo $this->__('What\'s New?') ?></h3>
</div>
<?php
    // some helpers
    $_helper = $this->helper('catalog/output');
    $storeId = Mage::app()->getStore()->getId();
    $catalog = $this->getLayout()->createBlock('catalog/product_list')
    ->setStoreId($storeId);
    
    // get all products that are marked as featured
    $collection = Mage::getModel('catalog/product')->getCollection();
    $collection->addAttributeToSelect('home_new_products');
    $collection->addFieldToFilter(array(array('attribute' => 'home_new_products', 'eq' => true)));
    
    // if no products are currently featured, display some text
    if (!$collection->count()) :
    ?>
<p><?php echo $this->__('There are no new products at the moment.') ?></p>
<?php else : ?>
    <?php
        $_collectionSize = $collection->count();
        $_columnCount = 4;
        $i = 0;
        
        foreach ($collection as $_product) :
            $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());
        
        ?>
    <?php if ($i++%$_columnCount==0): ?>
    <ul class="products-grid grid-recent">
        <?php endif ?>
        <li class="item">
            <p class="product-image">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product,'small_image'),null, true) ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(100); ?>" width="100" height="100" alt="<?php echo $this->stripTags($this->getImageLabel($_product,'small_image'),null, true) ?>" />
                </a>
            </p>
            <h5 class="product-name">
                <a href="<?php echo $_product->getProductUrl()?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                </a>
            </h5>
            <div class="price-box">
                <span class="regular-price">
                    <?php echo Mage::helper('core')->currency($_product->getPrice()); ?>
                </span>
            </div>
                
            <?php if($_product->getRatingSummary()): ?>
            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            <?php endif; ?>
            <?php echo $this->getPriceHtml($_product, true) ?>
            <div>
            <?php if($_product->isSaleable()): ?>
                <div class="actions">
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" onclick="setLocation('<?php echo $catalog->getAddToCartUrl($_product) ?>')">
                        <?php echo $this->__('Add to Cart') ?>
                    </button>
                </div>
            <?php else: ?>
                <p><span><?php echo	$this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <!--ul>
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                <?php endif; ?>
                <?php if($_compareUrl=$catalog->getAddToCompareUrl($_product)): ?>
                    <li><span>|</span> <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                <?php endif; ?>
            </ul-->
            </div>
        </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
    </ul>
    <?php endif ?>
    <?php endforeach ?>
    <script type="text/javascript">
        decorateGeneric($$('ul.products-grid'),['odd','even','first','last']);
    </script>
<?php endif ?>