<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<?php $themeHelper = Mage::helper('itactica_intenso'); ?>
<?php $smallLogo = ($this->getLogoSrcSmall()) ? $this->getLogoSrcSmall() : $this->getLogoSrc(); ?>
<?php $isStickyEnabled = $themeHelper->stickyMenuUrl(); ?>
<?php //$isStoreSwitchEnabled = $themeHelper->storeSwitcher(); ?>

<header class="main-header<?php if ($themeHelper->stickyMenu()): ?> sticky-menu<?php endif; ?>">
   
    <!-- <div class="row top-header">
        <div class="small-6 medium-3 large-3 logo-container columns">
            &nbsp;
        </div>
        <div class="small-6 medium-3 medium-push-6 large-3 large-push-6 icons-for-small columns text-right">
            <?php if (!$themeHelper->secMenuTop()): ?>
            <div class="welcome-message show-for-medium-up"><?php echo $themeHelper->getAdditionalInfo(); ?></div>
            <?php endif; ?>
            <a href="#" class="right-off-canvas-toggle show-for-small-only icon-main-menu"></a> <a href="<?php echo $this->getUrl('checkout/cart'); ?>" class="hide-for-large-up icon-cart"></a> <a href="<?php echo $this->getUrl('customer/account'); ?>" class="show-for-medium-only icon-user"></a>
        </div>
        <div class="medium-6 large-6 medium-pull-3 large-pull-3 columns">
            &nbsp;
        </div>
    </div> -->
    <?php echo $this->getChildHtml('topMenu') ?>
</header>
 <!-- just testing a seperate products search bar, need to figure out search that will cover both store and content-->
    <!-- <div class="row">
        <div class="large-3 large-offset-9">
    <?php $catalogSearchHelper =  $this->helper('catalogsearch'); ?>
            <form method="get" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" id="search_mini_form">
                <div class="form-search">
                    <div class="action">
                        <button class="button" title="Search" type="submit"><span aria-hidden="true" class="icon-search"></span></button>
                        
                    </div>
                    <?php echo $this->getChildHtml('topSearch') ?>
                </div>
            </form>
        </div>
        </div> -->