<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<?php $themeHelper = Mage::helper('itactica_intenso'); ?>
<?php $smallLogo = ($this->getLogoSrcSmall()) ? $this->getLogoSrcSmall() : $this->getLogoSrc(); ?>
<?php $isStickyEnabled = $themeHelper->stickyMenuUrl(); ?>
<?php //$isStoreSwitchEnabled = $themeHelper->storeSwitcher(); ?>

<header class="main-header<?php if ($themeHelper->stickyMenu()): ?> sticky-menu<?php endif; ?>">
    <?php echo $this->getChildHtml('topMenu') ?>
</header>