<?php
/**
 * Intenso Premium Theme - pregelmaster customizations
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
/**
 * @var Mage_Page_Block_Html_Topdrawerlinks $this
 */
?>
<?php $themeHelper = Mage::helper('itactica_intenso'); ?>
<?php $isStoreSwitchEnabled = $themeHelper->storeSwitcher(); ?>
<?php if ($themeHelper->secMenuTop() && $themeHelper->showSecondaryMenu()): ?>
    <!-- <div class="row header-ribbon show-for-medium-up"> -->
    <div class="notice-bar show-for-medium-up">
    <div class="row">
        <div class="large-6 columns">
            <?php echo $this->getChildHtml('currency_selector') ?>
            <?php echo $this->getChildHtml('store_language') ?>
            <?php if ($isStoreSwitchEnabled) echo $this->getChildHtml('store_switcher') ?>
        </div>
    	<div class="large-6 columns">
    		<?php $catalogSearchHelper =  $this->helper('catalogsearch'); ?>
            <form method="get" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" id="search_mini_form">
                <div class="form-search">
                    <div class="action">
                        <button class="button" title="Search" type="submit"><span aria-hidden="true" class="icon-search"></span></button>                   
                    </div>
                    <?php echo $this->getChildHtml('topSearch') ?>    
                </div>
            </form>
    	</div>
        
    </div>
</div>
    <?php endif; ?>

	<div class="hide-for-small-only" id="second-top-bar-menu">

		<div id="top-bar-drawer">
       
       
        <div class="row">


        	<div class="large-5 columns">
			<div class="secondary-top-bar-left">

				<ul class="loc-menu">
					<li class="loc-title"><i class="loc-icon fi-web"></i>Country</li>
					<ul class="left">
						<li><a href="#">PreGel Canada</a></li>
						<li><a href="#">PreGel Mexico</a></li>
						<li><a href="#">PreGel Brasil</a></li>
						<li><a href="#">PreGel Colombia</a></li>
					</ul>
					<ul class="left">
						<li><a href="#">PreGel Ecuador</a></li>
						<li><a href="#">PreGel Latin America</a></li>
						<li><a href="#">Headquarters - PreGel Italy</a></li>
						<li><a href="#">More Locations Around the World</a></li>
					</ul>
				</ul>
			</div>
		</div>



		<div class="large-7 columns">
			<div class="secondary-top-bar-right">
				<ul id="menu-secondary-top-bar" class="top-simple-menu">
					<li id="menu-item" class="menu-item"><a href="http://pregeltest.com/news/">News</a></li>
					<li id="menu-item-61" class="menu-item"><a href="http://pregeltest.com/events/">Events</a></li>
					<li id="menu-item-46" class="menu-item"><a href="http://pregeltest.com/recipes/">Recipes</a></li>
					<li id="menu-item-51" class="menu-item"><a href="http://pregeltest.com/resources/">Resources</a>
						<ul class="menu">
							<li id="menu-item-54" class="menu-item"><a href="http://pregeltest.com/resources/blog/">Blog</a></li>
							<li id="menu-item-57" class="menu-item"><a href="http://pregeltest.com/resources/videos/">Videos</a></li>
						</ul>
					</li>
					<li id="menu-item-177" class="menu-item"><a href="http://pregeltest.com/contact/">Contact</a>
					    <ul class="menu">
					    	<li><i class="fi-telephone"></i>1.555.555.5555</li>
					    </ul>
					</li>

					<!-- <li> -->
						<?php //if ($themeHelper->secMenuTop() && $themeHelper->showSecondaryMenu()): ?>
   <!--  <div class="row header-ribbon show-for-medium-up"> -->
        <!-- <div class="small-12 columns"> -->
            <?php //echo $this->getChildHtml('currency_selector') ?>
            <?php //echo $this->getChildHtml('store_language') ?>
            <?php //if ($isStoreSwitchEnabled) echo $this->getChildHtml('store_switcher') ?>
           <!--  <span class="welcome-message"><?php //echo $themeHelper->getAdditionalInfo(); ?></span>
            <?php //echo $this->getChildHtml('sec_menu_links') ?> -->
        <!-- </div> -->
   <!--  </div> -->
    <?php //endif; ?>
					<!-- </li> -->


				</ul>	
				<span class="nav-close"></span>
			</div>
		</div>

	</div>


		</div>
	</div>