<?php
/**
 * Intenso Premium Theme
 * 
 * @category    Itactica
 * @package     Itactica_Intenso
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php 
$_menu = $this->getHtml('level-top');
$_linksArray = @unserialize(Mage::getStoreConfig('intenso/header/main_menu_links', Mage::app()->getStore()));
$_offcanvasLinksArray = @unserialize(Mage::getStoreConfig('intenso/header/mobile_offcanvas_links', Mage::app()->getStore()));
?>
<nav class="top-bar right-off-canvas-menu expanded main-nav <?php echo Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()); ?>" data-topbar>
    <ul class="title-area">
        <li class="name show-for-small-only">
            <?php echo $this->getChildHtml('offcanvasSearch') ?>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><?php echo $this->__('Menu'); ?></a></li>
    </ul>
    <!-- <section class="top-bar-section clearfix"> -->
    <section class="row top-bar-section clearfix">
        <!-- Left Nav Section -->
    <ul class="left">
       <?php if (Mage::getStoreConfig('intenso/header/show_home_link', Mage::app()->getStore()) ||
                Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?>
        <li class="<?php if (Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?> show-for-small-only<?php endif; ?>">
          <a href="http://pregel2.com"><!-- <a href="http://pregel2.com"> --><span class="show-for-small-only icon-home"></span><?php echo $this->__('Home'); ?></a>
        </li>
      <?php endif; ?>
      <?php if (Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?>
        <li class="has-dropdown hide-for-small-only vertical-menu-link">
          <a href="<?php echo $this->getUrl('') ?>">
            <span class="show-for-large-only sup"><?php echo $this->__('Shop by'); ?></span>
            <span class="vmenu-title"><?php echo $this->__('Category'); ?></span>
          </a>
        </li>
      <?php endif; ?>
      <?php if (Mage::getStoreConfig('intenso/header/show_categories', Mage::app()->getStore())): ?>
        <li class="show-for-small-only group-title"><?php echo $this->__('Shop'); ?></li>
        <?php if ($_menu): ?>
          <?php echo $_menu ?>
        <?php endif ?>
      <?php endif ?> 

      <!-- testing add links manually until can fully integrate menus -->
      <!-- <li class="has-dropdown hide-for-small-only vertical-menu-link"> -->
      <li class="has-dropdown-for-large reg">
        <a href="http://pregel-itc.com">Training</a>
          <ul class="level0 dropdown arrow-box">
                <li class="level1 menu-item"><a href="#">Link</a></li>
                <li class="level1 menu-item"><a href="#">Link</a></li>
                <li class="level1 menu-item"><a href="#">Link</a></li>
          </ul>
      </li>

<!-- this would add links through admin -->
     <!-- <?php if ($_linksArray): ?>
        <?php foreach ($_linksArray as $menuItem): ?>
          <li class="custom-menu<?php if ($menuItem['static_block']): ?> has-dropdown-for-large<?php endif; ?>">
            <a href="<?php echo rtrim($this->getUrl($menuItem['url']), '/'); ?>"><?php echo $menuItem['menu_item']; ?></a>
            <?php if ($menuItem['static_block']): ?>
              <div class="dropdown arrow-box">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($menuItem['static_block'])->toHtml(); ?>
              </div>
            <?php endif; ?>
          </li>
        <?php endforeach; ?>
      <?php endif; ?>
      <li class="show-for-small-only group-title"><?php echo $this->__('Pages'); ?></li>
      <li class="show-for-small-only"><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $this->__('Cart'); ?></a></li>
      <?php if ($_offcanvasLinksArray): ?>
        <?php foreach ($_offcanvasLinksArray as $menuItem): ?>
          <li class="show-for-small-only"><a href="<?php echo rtrim($this->getUrl($menuItem['url']), '/'); ?>"><?php echo $menuItem['menu_item']; ?></a></li>
        <?php endforeach; ?>
      <?php endif; ?> -->
    </ul> 
        <!-- Right Nav Section -->
        <ul class="right show-for-large-up">
            <li class="has-dropdown hide-for-small-only vertical-menu-link"><a href="http://pregel2.com/about-us">About Us</a>
              <ul class="level0 dropdown arrow-box">
                <li class="level1 menu-item"><a href="http://pregel2.com/about-us/history/">History</a></li>
                <li class="level1 menu-item"><a href="http://pregel2.com/about-us/marco-casol/">Marco Casol</a></li>
                <li class="level1 menu-item"><a href="http://pregel2.com/about-us/around-the-world/">Around the World</a></li>
                <li class="level1 menu-item"><a href="http://pregel2.com/about-us/distribution-warehousing/">Distribution &#038; Warehousing</a></li>
                <li class="level1 menu-item"><a href="http://pregel2.com/about-us/product-manufacturing-standards/">Product Manufacturing Standards</a></li>
                <li class="level1 menu-item"><a href="http://pregel2.com/about-us/vision-and-values/">Vision and Values</a></li>
                <li class="level1 menu-item"><a href="http://pregel2.com/about-us/our-team/">Our Team</a></li>
                <li class="level1 menu-item"><a href="http://pregel2.com/about-us/career-opportunities/">Career Opportunities</a></li>
              </ul>
            </li>
            <li class="has-dropdown hide-for-small-only vertical-menu-link"><a href="http://pregel2.com/services">Services</a>
              <ul class="level0 dropdown arrow-box">
                <li class="level1 menu-item"><a href="http://pregel2.com/services/customer-support/">Customer Support</a></li>
                <li class="level1 menu-item"><a href="http://pregel2.com/services/private-labeling/">Private Labeling</a></li>
                <li class="level1 menu-item"><a href="http://pregel2.com/services/research-and-development/">Research and Development</a></li>
             </ul>
            </li>

            <li class="has-dropdown hide-for-small-only">
                <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><span aria-hidden="true" class="icon-cart"></span><span class="sup"><?php echo trim($this->getChildHtml('cart_summary')); ?> <?php echo $this->__('items'); ?></span><?php echo $this->__('Cart'); ?></a>
                <ul class="dropdown cart-dropdown">
                    <li class="arrow-box">
                        <?php echo $this->getChildHtml('minicart_head'); ?>
                    </li>
                </ul>
            </li>
        </ul>

    <div id="pglogo">
       <!-- <div class="logo-container"> -->
            <a href="http://pregel2.com">
               <img class="main-logo" src="http://products.pregel2.com/skin/frontend/intenso/default/images/pregel-logo.svg" alt="Pregel" title="Pregel">
                <!-- <img class="main-logo-small" src="http://store.pregeltest.com/skin/frontend/intenso/default/images/pregel-logo.svg" alt="Pregel" title="Pregel"> -->
               <!--  <?php if (!empty($isStickyEnabled)): ?>
                <?php $stickyLogo = $this->getSkinUrl($themeHelper->stickyMenuUrl()); ?>
                <img class="main-logo-sticky" src="<?php echo $stickyLogo ?>" alt="<?php echo $this->getLogoAlt() ?>" title="<?php echo $this->getLogoAlt() ?>" />
                <?php endif; ?> -->
            </a>
<!-- </div> -->

    </div>
  
	</section>
</nav>