<?php
/**
 * Intenso Premium Theme
 * 
 * @category    Itactica
 * @package     Itactica_Intenso
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Top cart for menu
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php 
//$_menu = $this->getHtml('level-top');
//$_linksArray = @unserialize(Mage::getStoreConfig('intenso/header/main_menu_links', Mage::app()->getStore()));
//$_offcanvasLinksArray = @unserialize(Mage::getStoreConfig('intenso/header/mobile_offcanvas_links', Mage::app()->getStore()));
?>
<ul class="right show-for-large-up pgbar-cart">
    <!-- <li class="has-dropdown hide-for-small-only"> -->
    <li class="has-dropdown hide-for-small-only">
      <a href="<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) { echo $this->getUrl('customer/account'); } else { echo Mage::helper('customer')->getLoginUrl(); } ?>"><span class="sup truncate"><?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?><?php echo $this->__('Hello, %s', Mage::getSingleton('customer/session')->getCustomer()->getFirstname()); ?><?php else: ?><?php echo $this->__('Hello. Sign in'); ?><?php endif; ?></span><?php echo $this->__('Your Account'); ?></a>
      <ul class="dropdown account-dropdown">
        <li class="arrow-box">
            <div class="bg-box">
              <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
              <a href="<?php echo $this->getUrl('customer/account/logout'); ?>" class="button sign-in"><?php echo $this->__('Log Out'); ?></a>
          <?php else: ?>
          <a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>" class="button sign-in"><?php echo $this->__('Sign in'); ?></a>
          <p class="small"><?php echo $this->__('New customer?'); ?> <a href="<?php echo $this->getUrl('customer/account/create'); ?>" ><?php echo $this->__('Start here'); ?></a>.</p>
      <?php endif; ?>
  </div>
  <?php echo $this->getChildHtml('topLinks') ?>
</li>
</ul>
</li>
<li class="has-dropdown hide-for-small-only"> 
    <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><span aria-hidden="true" class="icon-cart"></span><span class="sup"><?php echo trim($this->getChildHtml('cart_summary')); ?> <?php echo $this->__('items'); ?></span><?php echo $this->__('Cart'); ?></a>
    <ul class="dropdown cart-dropdown">
        <li class="arrow-box">
            <?php echo $this->getChildHtml('minicart_head'); ?>
        </li>
    </ul>
</li>

<!-- testing -->
<li class="has-dropdown hide-for-small-only"> 
<!-- Cart2Qoute -->
                <div class="header-miniquote">
                    <?php echo $this->getChildHtml('miniquote_head'); ?>
                </div>
 <!-- <ul class="dropdown cart-dropdown">
        <li class="arrow-box">
                 <?php //echo $this->getChildHtml("miniquote_content"); ?>
        </li>
      </ul> -->



</li>
</ul>