<?php
/**
 * Intenso Premium Theme
 * 
 * @category    Itactica
 * @package     Itactica_Intenso
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Top menu for wordpress
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>

<!-- <ul id="mobile-wp-prod-menu" class="vertical menu" data-accordion-menu=""> -->
<!-- <ul id="mobile-wp-prod-menu" class="vertical menu" data-drilldown> -->
    <?php
        $obj = new Mage_Catalog_Block_Navigation();
        $storeCategories = $obj->getStoreCategories();
        Mage::registry('current_category') ? $currentCategoryId = Mage::registry('current_category')->getId() : $currentCategoryId='';
        foreach ($storeCategories as $_category):
    ?>
            <!-- <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children has-submenu is-accordion-submenu-parent"> -->
            <li>
               <!--  <?php //echo '<a href="' . $_category->getUrl() . '">' ?><strong><?php //echo $_category->getName(); ?></strong></a> -->
                <a href="http://products.pregel2.com/products.html"><?php echo $_category->getName(); ?></a>
                <?php $categoryChildren = $_category->getChildren(); ?>
                <?php if($categoryChildren->count()) : ?>
                   <!--  <ul class="vertical nested menu submenu is-accordion-submenu" data-submenu="" style="display: none;"> -->
                   <ul class="vertical menu">
 
                        <?php foreach($categoryChildren as $_categoryChild) : ?>
                            <?php $_categoryChildModel = Mage::getModel('catalog/category')->load($_categoryChild->getId());?>
                            <?php $categoryGrandchildren=$_categoryChild->getChildren(); ?>
                            <!-- <li class="menu-item menu-item-type-post_type menu-item-object-page is-submenu-item is-accordion-submenu-item"> -->
                             <li>
                                <?php
                                    $currentCategoryId===$_categoryChild->getId() ? $bold="style=\"font-weight:bold\"" : $bold='';
                                    echo '&emsp;' . '<a href="' . $_categoryChildModel->getUrl() . '"' . $bold . '>' .  $_categoryChild->getName() . '</a>';
                                ?>
                                <?php if($categoryGrandchildren->count()) : ?>
                                <ul class="menu vertical">
                                <?php foreach($categoryGrandchildren as $_categoryGrandchild) : ?>
                                    <?php $_categoryGrandchildModel = Mage::getModel('catalog/category')->load($_categoryGrandchild->getId());?>
                                   
                                    <li>
                                        <?php
                                            $currentCategoryId===$_categoryChild->getId() ? $bold="style=\"font-weight:bold\"" : $bold='';
                                            echo '&emsp;&emsp;' . '<a href="' . $_categoryGrandchildModel->getUrl() . '"' . $bold . '>' .  $_categoryGrandchild->getName() . '</a>';
                                        ?>
                                    </li>

                                <?php endforeach; ?>
                              </ul>
                            <?php endif; ?>
                            </li>
                            
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endforeach ?>
    <!-- </ul> -->