<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php $helper = Mage::helper('itactica_intenso'); ?>
<footer class="footer" role="contentinfo">
	<div id="inner-footer" class="row">

		<div id="" class="large-4 medium-6 small-12 columns">

			<!-- <div id="call-to-action-row" class="">
					<div class="small-12 columns row"><label><h4>Sign Up for Our Newsletter</h4></label></div>
					<div class="row">
						 <form action="https://go.pardot.com/l/95432/2016-10-13/2k8pnr" method="post">
			                <div class="small-9 columns">
			                     <input id="footer-input" type="email" name="email" required="required" placeholder="example@pregelaustralia.com" />
			               </div>
			               <div id="footer-button-column" class="small-3 columns">
			                     <input id="footer-button" class="button" type="submit" value="submit" required="required" />
			               </div>
			         </form>
					</div>
				</div> -->

			<div id="subsidiaries-row" class="large-9 medium-9 small-9">
				<a href="https://pregel.com.au/locations/">
					<div class="row">
						<div id="sub-containers" class="small-2 columns">
							<div id="global-img"></div>
						</div>
						<div id="sub-containers" class="small-10 columns">
							<h4 id="global-text" class="text-left">View All PreGel Subsidiaries</h4>
						</div>
					</div>
				</a></div>

					
			</div>

			<div class="large-4 medium-6 columns">
				
			</div>
			<div id="right-footer-links" class="large-3 columns">
				<ul class="footer-links">
		 <li class="text-left">
			<a href="https://asia.pregel2.com/contact/">Contact Us</a>
		 </li>
		 <li class="text-left">
			<a href="https://asia.pregel2.com/privacy-policy/">Privacy Policy</a>
		 </li>
		 <li class="text-left">
			<a href="https://asia.pregel2.com/terms-of-use/">Terms of Use</a>
		 </li>						
		</ul>
			</div>
		</div> 
		<div id="bottom-footer" class="row-expanded">
		 <div class="row">
			<div id="footer-contact-info" class="large-12 columns">
				<p class="large-3 medium-3 small-12 text-center columns">PreGel ASIA</p>
				<p class="large-3 medium-3 small-12 text-center columns">XXXXXXX</p>
				<p class="large-3 medium-3 small-12 text-center columns">XXXXXXXX</p>
				<p class="large-3 medium-3 small-12 text-center columns">Tel: XX XXXX XXXX</p>
			</div>
		  <div class="large-12 medium-12 small-12 text-center columns">
		  <p id="copyright" class="source-org copyright">&copy; PreGel. All rights reserved.</p>
		  </div>
		 </div>
		</div>
	</footer> <!-- end .footer -->
