<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php $helper = Mage::helper('itactica_intenso'); ?>
<footer class="footer" role="contentinfo">
	<div id="inner-footer" class="row">

		<div id="" class="large-4 medium-6 small-12 columns">

			<div id="call-to-action-row" class="">
					<div class="small-12 columns row"><label><h4>Suscríbete al Newsletter</h4></label></div>
					<div class="row">
						 <form action="https://go.pardot.com/l/95432/2016-10-13/2k8pnr" method="post">
			                <div class="small-9 columns">
			                     <input id="footer-input" type="email" name="email" required="required" placeholder="ejemplo@pregelmexico.com" />
			               </div>
			               <div id="footer-button-column" class="small-3 columns">
			                     <input id="footer-button" class="button" type="submit" value="enviar" required="required" />
			               </div>
			         </form>
						<!-- <div class="small-9 columns">
							<input id="footer-inpet" type="text" placeholder="example@pregelamerica.com" />
						</div>
						<div id="footer-button-column" class="small-3 columns">
							<a href="" id="footer-button" class="button">Submit</a>
						</div> -->
					</div>
				</div>

			<div id="subsidiaries-row" class="large-9 medium-9 small-9">
				<a href="https://mexico.pregel2.com/locations/">
					<div class="row">
						<div id="sub-containers" class="small-2 columns">
							<div id="global-img"></div>
						</div>
						<div id="sub-containers" class="small-10 columns">
							<h4 id="global-text" class="text-left">Ver todas las subsidiarias de PreGel</h4>
						</div>
					</div>
				</a></div>

					
			</div>

			<div class="large-4 medium-6 columns">
				<ul class="footer-social text-center">
					<li>
						<a href="https://www.facebook.com/pregelmexico/" target="_blank">
							<!-- <i class="fi-social-facebook"></i> -->
							<i class="icon-facebook" style="color: #6ba0d3; font-size: 40px; margin: 0 5px;"></i>
						</a>
					</li>
					<!-- <li>
						<a href="https://twitter.com/PreGelCANADA" target="_blank">
							<i class="icon-twitter" style="color: #6ba0d3; font-size: 40px; margin: 0 5px;"></i>
						</a>
					</li> -->
					<li>
						<a href="https://www.linkedin.com/company/482070" target="_blank">
							<!-- <i class="fi-social-linkedin"></i> -->
							<i class="icon-linkedin" style="color: #6ba0d3; font-size: 40px; margin: 0 5px;"></i>
						</a>
					</li>
					<!-- <li>
						<a href="https://www.youtube.com/user/PreGelAMERICA" target="_blank">
							<i class="icon-youtube" style="color: #6ba0d3; font-size: 40px; margin: 0 5px;"></i>
						</a>
					</li> -->
					<li>
						<a href="https://www.pinterest.com/pregelamerica/pregel-mexico/" target="_blank">
							<!-- <i class="fi-social-pinterest"></i> -->
							<i class="icon-pinterest" style="color: #6ba0d3; font-size: 40px; margin: 0 5px;"></i>
						</a>
					</li>
					<li>
						<a href="https://www.instagram.com/pregelmexico/" target="_blank">
							<!-- <i class="fi-social-instagram"></i> -->
							<i class="icon-instagram" style="color: #6ba0d3; font-size: 40px; margin: 0 5px;"></i>
						</a>
					</li>
				</ul>
			</div>
			<div id="right-footer-links" class="large-3 columns">
				<ul class="footer-links">
		 <li class="text-left">
			<a href="http://spain.pregel2.com/oportunidades-de-carrera/">Oportunidades profesionales</a>
		 </li>
		 <li class="text-left">
			<a href="https://mexico.pregel2.com/contactanos/">Contáctenos</a>
		 </li>
		 <li class="text-left">
			<a href="http://spain.pregel2.com/politica-de-privacidad/">Política de privacidad</a>
		 </li>
		 <li class="text-left">
			<a href="http://spain.pregel2.com/terminos-de-uso/">Términos de Uso</a>
		 </li>
		 <li class="text-left">
			<a href="http://spain.pregel2.com/politicas-de-devolucion/">Politica de envios</a>
		 </li>							
		</ul>
			</div>
		</div> 
	</footer> <!-- end .footer -->
	<div id="bottom-footer" class="row-expanded">
		 <div class="row">
			<div id="footer-contact-info" class="large-12 columns">
				<p class="large-2 medium-12 small-12 text-center columns">PreGel MEXICO</p>
				<p class="large-2 medium-4 small-12 text-center columns">Calle San Miguel 308</p>
				<p class="large-2 medium-4 small-12 text-center columns">Bodega n° 26</p>
				<p class="large-2 medium-4 small-12 text-center columns">Zapopan, Jalisco CP 45110</p>
				<p class="large-2 medium-6 small-12 text-center columns">Tel: +52 33 3673 5773</p>
				<p class="large-2 medium-6 small-12 text-center columns">Tel: +52 33 3673 6428</p>
			</div>
		  <div class="large-12 medium-12 small-12 text-center columns">
		  <p id="copyright" class="source-org copyright">© 2017 PreGel Mexico. All rights reserved.</p>
		  </div>
		 </div>
		</div>
