<reference name="top_slider">
<block type="cms/block"  name="showcase">
    <action method="setBlockId">
      <block_id>showcase</block_id>
    </action>
  </block>
</reference>
<reference name="content">
 <block type="catalog/product_new" name="home.product.new" alias="product_new" template="catalog/product/new.phtml">
    <action method="setProductsCount"><count>8</count></action>
    <action method="addPriceBlockType">
      <type>bundle</type>
      <block>bundle/catalog_product_price</block>
      <template>bundle/catalog/product/price.phtml</template>
    </action>
  </block>
</reference>
<remove name="right.newsletter"/>