<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
?>
<?php $catalogSearchHelper =  $this->helper('catalogsearch'); ?>

<form method="get" action="https://pgbxproducts.pregel2.com/fr-pgbx/catalogsearch/result/" id="search_mini_form">
                <div class="form-search">
                    <div class="action">
                        <button class="button" title="Search" type="submit"><i aria-hidden="true" class="fi-zoom-in"></i></button>
                    </div>
<div class="search-box">
    <input placeholder="Search all products..." type="text" class="input-text placeholder" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" id="search" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" />
    <label for="search"><?php echo $this->__('FR Search entire store here...') ?></label>
    
    <div class="search-autocomplete" id="search_autocomplete"></div>
    <!-- <script type="text/javascript">
    //<![CDATA[
        //var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
        //searchForm.initAutocomplete('<?php //echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
    //]]>
    </script> -->
</div>
</div>
</form>
