<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php
    $_baseUrl = Mage::getBaseUrl();
    $_currentUrl = Mage::helper('core/url')->getCurrentUrl();
    $_relativeUrl = str_replace($_baseUrl, '/', $_currentUrl);
?>
<?php 
    $_description = $_product->getDescription();
    $_attributes = new Mage_Catalog_Block_Product_View_Attributes();
    $_attributes->setProduct($_product->getId());
    $_additional = $_attributes->getAdditionalData();
    $_reviews = false;
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<section role="main" itemtype="http://schema.org/Product" itemscope>
    <div class="row product-view">
        <meta content="<?php echo $_relativeUrl; ?>" itemprop="url">
        <!-- Product Pic & Info -->
        <div class="small-12 product-essential columns">
            <div class="row">
                <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                    <?php echo $this->getBlockHtml('formkey') ?>
                    <div class="no-display">
                        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                        <input type="hidden" name="related_product" id="related-products-field" value="" />
                    </div>
                    <!-- First Column: Product Image -->
                    <?php echo $this->getChildHtml('media') ?>

                    <!-- Central Column: Product info -->
                    <div class="small-12 medium-6 product-shop columns">
                        <h1 itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                        <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                        <?php echo $this->getChildHtml('extrahint') ?>
                        <?php echo $this->getChildHtml('alert_urls') ?>
                        <?php echo $this->getChildHtml('media_mobile') ?>
                        <?php echo $this->getChildHtml('product_type_data') ?>
                        <?php echo $this->getTierPriceHtml() ?>
                        <!-- testing certification logos -->
                       <div class="certifications">

                         <?php if ($targetValues = $_product->getAttributeText('certifications')) {
                                echo ('CERTIFICATIONS: ');
                                    if (is_string($targetValues)) {
                                        $targetValues = array($targetValues);
                                        $lastItem = end($targetValues);
                                    }
                                        foreach($targetValues as $_target) :?>
                                         <img src="/media/certifications/<?php echo $_target ?>.png"></img>

                                        <?php endforeach;
                                                 }
                                ?>
                       </div>
                       <!-- testing code -->
                        <p><?php echo $this->__('CODE: ') . $this->htmlEscape($_product->getData('code')); ?></p>
                        <!-- testing sku -->
                        <p><?php echo $this->__('(will be hidden)SKU: ') . $this->htmlEscape($_product->getData('sku'));?></p>
                        <!-- testing dimensions -->
                        <p><?php if ($_product->getData('dimensions')) {
                            echo $this->__('DIMENSIONS: ') . $this->htmlEscape($_product->getData('dimensions')); 
                        } ?></p>
                        <!-- testing packaging -->
                        <p><?php if ($_product->getData('packaging')) {
                        echo $this->__('PACKAGING: ') . $this->htmlEscape($_product->getData('packaging')); 
                        } ?></p>
                        <!-- testing display weight -->
                        <p><?php if ($_product->getData('product_weight')) {
                        echo $this->__('WEIGHT: ') . $this->htmlEscape($_product->getData('product_weight')); 
                        } ?></p>
                        <!-- testing material -->
                         <p>
                             <?php if ($targetValues = $_product->getAttributeText('material')) {
                                 $lastItem = end($targetValues);
                                echo ('MATERIAL: ');
                                    if (is_string($targetValues)) {
                                        $targetValues = array($targetValues);
                                    }
                                        foreach($targetValues as $_target) :
                                         echo $_target;
                                         if($_target != $lastItem) echo ", ";

                                         endforeach;
                                                 }
                                ?>
                         </p>
                        <!-- testing application -->
                         <p>
                             <?php if ($targetValues = $_product->getAttributeText('application')) {
                                 $lastItem = end($targetValues);
                                echo ('APPLICATIONS: ');
                                    if (is_string($targetValues)) {
                                        $targetValues = array($targetValues);
                                    }
                                        foreach($targetValues as $_target) :
                                         echo $_target;
                                         if($_target != $lastItem) echo ", ";

                                         endforeach;
                                                 }
                                ?>
                         </p>
                         <!-- testing color -->
                        <p><?php if ($_product->getData('color')) {
                        echo $this->__('COLOR: ') . $this->htmlEscape($_product->getAttributeText('color')); 
                        } ?></p>


                        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                        <?php endif;?>

                        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                        <?php endif;?>

                        <?php if ($_product->getShortDescription()):?>
                            <div class="short-description hide-for-small-only">
                                <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                            </div>
                        <?php endif;?>
                        <?php echo $this->getChildHtml('other');?>
                        <!-- Buy Box -->
                        <div class="product-shop-side">
                         <?php if ($_product->isSaleable()):?>
                            <?php echo $this->getChildChildHtml('product_buy_box', '', true, true) ?>
                        <?php endif;?>
                        <!-- override for Add to Quote buttons -->
                         <!-- Cart2Quote button -->
                            <?php if(!$_product->isSaleable()): ?>
                                <?php echo Mage::app()->getLayout()->createBlock('qquoteadv/qquotebtn')
                                                ->setData('product', $_product)
                                                ->setTemplate('qquoteadv/catalog/product/view/addtoquoteadv.phtml')
                                                ->toHtml(); ?>
                           <?php endif; ?>
                        <!-- end Cart2Quote button -->


                      

                        <?php if ($this->canEmailToFriend()): ?>
                            <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
                        <?php endif; ?>
                        <?php if (Mage::getModel('cms/block')->load('product_view_block_1')->getIsActive()): ?>
                            <div class="product-view-block-1">
                                <?php echo $this->getChildHtml('product_view_block_1') ?>
                            </div>
                        <?php endif; ?>
                        </div>
                    </div>
                </form>
                <script type="text/javascript">
                //<![CDATA[
                    var productAddToCartForm = new VarienForm('product_addtocart_form');
                    productAddToCartForm.submit = function(button, url) {
                        <?php if(Mage::helper('itactica_intenso')->formFieldsType() == 'mdformfields'): ?>
                        Object.extend(Validation, {
                            isVisible : function(elm) {
                                while(elm.tagName != 'BODY') {
                                    // validate hidden select boxes when chosen.js is enabled
                                    if (elm.className.indexOf('super-attribute-select') > -1 || elm.className.indexOf('product-custom-option') > -1) {
                                        elm = elm.parentNode;
                                    }
                                    if(!$(elm).visible()) return false;
                                    elm = elm.parentNode;
                                }
                                return true;
                            }    
                        });
                        <?php endif; ?>
                        if (this.validator.validate()) {
                            var form = this.form;
                            var oldUrl = form.action;

                            if (url) {
                               form.action = url;
                            }
                            var e = null;
                            try {
                                this.form.submit();
                            } catch (e) {
                            }
                            this.form.action = oldUrl;
                            if (e) {
                                throw e;
                            }

                            if (button && button != 'undefined') {
                                button.disabled = true;
                            }
                        }
                    }.bind(productAddToCartForm);

                    productAddToCartForm.submitLight = function(button, url){
                        if(this.validator) {
                            var nv = Validation.methods;
                            delete Validation.methods['required-entry'];
                            delete Validation.methods['validate-one-required'];
                            delete Validation.methods['validate-one-required-by-name'];
                            // Remove custom datetime validators
                            for (var methodName in Validation.methods) {
                                if (methodName.match(/^validate-datetime-.*/i)) {
                                    delete Validation.methods[methodName];
                                }
                            }

                            if (this.validator.validate()) {
                                if (url) {
                                    this.form.action = url;
                                }
                                this.form.submit();
                            }
                            Object.extend(Validation.methods, nv);
                        }
                    }.bind(productAddToCartForm);
                //]]>
                </script>
            </div>
        </div>
    </div>

<!-- TESTING RELATED PRODUCTS -->
<?php echo $this->getChildHtml('related_products') ?>

<div class="row">
    <div class="large-6 columns">
        <h4>RECIPES</h4>
       <!-- testing recipe basic  link -->
       <?php if($_product->getData('recipe_basic_id')): ?>
       <a class="button expand btn-recipe" href="http://pregelrecipes.com/recipe.php?recipeID=<?php echo $_product->getData('recipe_basic_id') ?>&cnt=america&lng=en" target="blank">View Basic Recipe for <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
   <?php endif; ?>

   <!-- testing ingredient recipes link  -->
   <?php if($_product->getData('recipe_ing_id')): ?>
   <a class="button expand btn-recipe" href="http://pregelrecipes.com/search.php?adv=yes&ingredient=<?php echo $_product->getData('recipe_ing_id') ?>&cnt=america&lng=en" target="blank">View All Recipes Using <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
<?php endif; ?>
</div>
<div class="large-6 columns">
    <p>Download catalog</p>
</div>
</div>

    <!-- Magellan Fixed Navigator -->
    <?php //echo $this->getChildHtml('product_nav'); ?>

    <div class="product-collateral-wrapper">
        <?php //echo $this->getChildHtml('upsell_products') ?>
        <!-- testing video -->
         <div class="row product-description">
            <h3>Product Videos</h3>
                <?php if($_product->getData('product_video')): ?>
                    <iframe width="560" height="315" src="http://www.youtube.com/embed/<?php echo $_product->getData('product_video') ?>" frameborder="0" allowfullscreen></iframe>
                <?php endif; ?>
        </div>

        <!-- testing - pull video block into loop, has not been added to layout yet -->
        <?php //echo $this->getChildHtml('video') ?>

        <?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>

            <?php if ($alias == "ratings-reviews"): ?>
                <?php $_reviews = true; ?>
                <?php echo $this->getChildHtml('custom_info') ?>
            <?php endif;?>
            <div class="product-collateral <?php echo "{$alias}"?> clearfix row">
                <?php echo $html; ?>
            </div>
        <?php endforeach;?>

        <?php if (!$_reviews): ?>
            <?php echo $this->getChildHtml('custom_info') ?>
        <?php endif; ?>

        <?php echo $this->getChildHtml('product_additional_data') ?>
        <?php //echo $this->getChildHtml('related_products') ?>


    </div>
</section>