<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!doctype html>
<html lang="en" class="no-js">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass(). Mage::helper('itactica_intenso')->getStoreClass() . ' ' . Mage::helper('itactica_intenso')->formFieldsType() .'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('topdrawerlinks') ?>
<div class="off-canvas-wrap">
    <div class="inner-wrap">
        <?php echo $this->getChildHtml('global_notices') ?>
        <?php echo $this->getChildHtml('header') ?>
        <?php echo $this->getChildHtml('breadcrumbs') ?>
        <?php echo $this->getChildHtml('global_messages') ?>
        <?php echo $this->getChildHtml('content') ?>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getAbsoluteFooter() ?>
        <a class="exit-off-canvas"></a>
    </div><!-- /inner-wrap -->
</div><!-- /off-canvas-wrap -->
<?php echo $this->getChildHtml('before_body_end') ?>
<div class="loading-bar"></div>

<!-- pardot tracking campaign PGA website -->
<script type="text/javascript">
piAId = '96432';
piCId = '1980';

(function() {
    function async_load(){
        var s = document.createElement('script'); s.type = 'text/javascript';
        s.src = ('https:' == document.location.protocol ? 'https://pi' : 'http://cdn') + '.pardot.com/pd.js';
        var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c);
    }
    if(window.attachEvent) { window.attachEvent('onload', async_load); }
    else { window.addEventListener('load', async_load, false); }
})();
</script>


</body>
</html>

