<?php
/**
 * Intenso Premium Theme
 * 
 * @category    Itactica
 * @package     Itactica_Intenso
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<script>
jQuery(document).ready(function(){   

  jQuery('body :not(script) .top-bar-section ul li a,body :not(script) h3#category-name' ).contents().filter(function() {
    return this.nodeType === 3;
    }).replaceWith(function() {
    return this.nodeValue.replace(/[™®©]/g, '<sup>$&</sup>');
    });

});
</script>
<?php 
$_menu = $this->getHtml('level-top');
$_linksArray = @unserialize(Mage::getStoreConfig('intenso/header/main_menu_links', Mage::app()->getStore()));
$_offcanvasLinksArray = @unserialize(Mage::getStoreConfig('intenso/header/mobile_offcanvas_links', Mage::app()->getStore()));
?>

<!-- <div id="pglogo">
 <a href="https://brasil.pregel2.com">
   <img class="main-logo" src="https://products.pregel2.com/skin/frontend/intenso/pregelmaster/images/pregel-logo.svg" alt="Pregel" title="Pregel">
 </a>
</div> -->

<nav class="top-bar right-off-canvas-menu expanded main-nav <?php echo Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()); ?>" data-topbar>
  <ul class="title-area">
   <!--  <li class="name show-for-small-only"> -->
   <!-- makrmark -->
    <li class="name hide-for-large-up">
      <?php echo $this->getChildHtml('offcanvasSearch') ?>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><?php echo $this->__('Menu'); ?></a></li>
  </ul>
  <section class="head-row top-bar-section clearfix <?php echo Mage::getStoreConfig('intenso/header/main_menu_event', Mage::app()->getStore()); ?>">
    <!-- <section class="row top-bar-section clearfix"> -->
    <!-- Left Nav Section -->

    <ul class="left">
     <?php if (Mage::getStoreConfig('intenso/header/show_home_link', Mage::app()->getStore()) ||
     Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?>
    <!--  <li class="<?php //if (Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?> show-for-small-only<?php //endif; ?>"> -->
    <!-- makrmark -->
     <li class="<?php if (Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?> hide-for-large-up<?php endif; ?>">
     <!--  <a href="http://pregel2.com"><span class="show-for-small-only icon-home"></span><?php //echo $this->__('Home'); ?></a> -->
     <!-- makrmark -->
      <a href="https://brasil.pregel2.com"><span class="hide-for-large-up icon-home"></span><?php echo $this->__('Home'); ?></a>
    </li>
  <?php endif; ?>
  <?php if (Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?>
 <!--  <li class="has-dropdown hide-for-small-only vertical-menu-link"> -->
 <!-- makrmark -->
  <li class="has-dropdown show-for-large-up vertical-menu-link">
    <a href="<?php echo $this->getUrl('') ?>">
      <span class="show-for-large-only sup"><?php echo $this->__('Shop by'); ?></span>
      <span class="vmenu-title"><?php echo $this->__('Category'); ?></span>
    </a>
  </li>
<?php endif; ?>
<?php if (Mage::getStoreConfig('intenso/header/show_categories', Mage::app()->getStore())): ?>
  <!-- <li class="show-for-small-only group-title"><?php //echo $this->__('Shop'); ?></li> -->
  <!-- makrmark -->
  <!-- <li class="hide-for-large-up group-title"><?php //echo $this->__('Shop'); ?></li> -->
  <?php if ($_menu): ?>
  <?php echo $_menu ?>
<?php endif ?>
<?php endif ?> 
<!-- manual mobile links for now -->
<!-- testing add links manually until can fully integrate menus -->
<!-- <li class="has-dropdown hide-for-small-only vertical-menu-link"> -->
<!-- <li class="has-dropdown-for-large reg"> -->
<!-- <li class="custom-dropdown has-dropdown hide-for-small-only vertical-menu-link"> -->
<!-- makrmark -->
<li class="custom-dropdown has-dropdown vertical-menu-link">
  <a href="https://brasil.pregel-itc.com/treinamento/pesquisar-classes/">Treienamento</a>
  <ul class="level0 dropdown arrow-box">
    <li class="level1 menu-item"><a href="https://brasil.pregel-itc.com/treinamento/pesquisar-classes/">Pesquisar Classes</a></li>
    <li class="level1 menu-item"><a href="https://brasil.pregel-itc.com/aulas/">Aulas</a></li>
    <li class="level1 menu-item"><a href="https://brasil.pregel-itc.com/training/calendar/">Calendário</a></li>
    <li class="level1 menu-item"><a href="https://brasil.pregel-itc.com/treinamento/unidades/">Unidades</a></li>
    <li class="level1 menu-item"><a href="https://brasil.pregel-itc.com/instrutores/">Instrutores</a></li>
    <li class="level1 menu-item"><a href="https://brasil.pregel-itc.com/perguntas-frequentes/">Perguntas Frequentes</a></li>
    <!-- <li class="level1 menu-item"><a href="#">Information &amp; Policies</a></li> -->
   <!--  <li class="level1 menu-item"><a href="https://staging.pregel-itc.com/training/faq/">FAQ</a></li> -->
    <li class="level1 menu-item"><a href="https://brasil.pregel-itc.com/minhas-reservas/">Minhas Reservas</a></li>
  </ul>
</li>

<!-- have to add mobile links manual for now, yes, they have to be repeated becuase of the split menu design-->
<li class="has-dropdown hide-for-large-up vertical-menu-link"><a href="#">Sobre a PreGel</a>
    <ul class="level0 dropdown arrow-box">
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/about/sobre-a-pregel-brasil/">Sobre a PreGel Brasil</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/about/pregel-worldwide/">PreGel Worldwide</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/about/visao-e-valores/">Visão e Valores</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/about/distribuicao-e-armazenamento/">Distribuição e Armazenamento</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/about/nossa-equipe/">Nossa Equipe</a></li>
      <!-- <li class="level1 menu-item"><a href="https://brasil.pregel2.com/">Our Team</a></li> -->
     <!--  <li class="level1 menu-item"><a href="https://brasil.pregel2.com/">Career Opportunities</a></li> -->
    </ul>
</li>
 <li class="has-dropdown hide-for-large-up vertical-menu-link"><a href="#">Recursos para Clientes</a>
    <ul class="level0 dropdown arrow-box">
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/servicos/ciencia-dos-alimentos-e-servicos-tecnicos/">Ciência dos Alimentos e Serviços Técnicos</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/servicos/marca-personalizada/">Marca Personalizada</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/servicos/perguntas-frequentes/">Perguntas Frequentes</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/servicos/servico-ao-cliente/">Serviço ao Cliente</a></li>
    </ul>
  </li>
<!-- end mobile manual links -->


<!-- this would add links through admin -->
<?php if ($_linksArray): ?>
  <?php foreach ($_linksArray as $menuItem): ?>
  <li class="custom-menu<?php if ($menuItem['static_block']): ?> has-dropdown-for-large<?php endif; ?>">
    <a href="<?php echo rtrim($this->getUrl($menuItem['url']), '/'); ?>"><?php echo $menuItem['menu_item']; ?></a>
    <?php if ($menuItem['static_block']): ?>
    <div class="dropdown arrow-box">
      <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($menuItem['static_block'])->toHtml(); ?>
    </div>
  <?php endif; ?>
</li>
<?php endforeach; ?>
<?php endif; ?>
<!-- <li class="show-for-small-only group-title"><?php //echo $this->__('Pages'); ?></li> -->
<!-- makrmark -->
<li class="hide-for-large-up group-title"><?php echo $this->__('More'); ?></li>
<!-- <li class="show-for-small-only"><a href="<?php //echo $this->getUrl('checkout/cart'); ?>"><?php //echo $this->__('Cart'); ?></a></li> -->
<!-- makrmark -->
<li class="hide-for-large-up"><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $this->__('Cart'); ?></a></li>
<?php if ($_offcanvasLinksArray): ?>
  <?php foreach ($_offcanvasLinksArray as $menuItem): ?>
 <!--  <li class="show-for-small-only"><a href="<?php //echo rtrim($this->getUrl($menuItem['url']), '/'); ?>"><?php //echo $menuItem['menu_item']; ?></a></li> -->
  <li class="hide-for-large-up"><a href="<?php echo rtrim($this->getUrl($menuItem['url']), '/'); ?>"><?php echo $menuItem['menu_item']; ?></a></li>
<?php endforeach; ?>
<?php endif; ?>


</ul> 

<!-- Right Nav Section -->
<!-- <ul class="right show-for-large-up"> -->
<ul class="right">
 <!--  <li class="has-dropdown hide-for-small-only vertical-menu-link"><a href="http://pregel2.com/about-us">About Us</a> -->
 <!-- makrmark -->
  <li class="has-dropdown show-for-large-up vertical-menu-link"><a href="https://brasil.pregel2.com/">Sobre a PreGel</a>
  <!-- <li class="has-dropdown vertical-menu-link"><a href="http://pregel2.com/about-us">About</a> -->
    <ul class="level0 dropdown arrow-box">
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/about/sobre-a-pregel-brasil/">Sobre a PreGel Brasil</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/about/pregel-worldwide/">PreGel Worldwide</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/about/visao-e-valores/">Visão e Valores</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/about/distribuicao-e-armazenamento/">Distribuição e Armazenamento</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/about/nossa-equipe/">Nossa Equipe</a></li>
      <!-- <li class="level1 menu-item"><a href="https://brasil.pregel2.com/">Our Team</a></li> -->
     <!--  <li class="level1 menu-item"><a href="https://brasil.pregel2.com/">Career Opportunities</a></li> -->
    </ul>
  </li>
  <!-- <li class="has-dropdown hide-for-small-only vertical-menu-link"><a href="https://brasil.pregel2.com/services">Services</a> -->
  <!-- makrmark -->
  <li class="has-dropdown show-for-large-up vertical-menu-link"><a href="#">Recursos para Clientes</a>
 <!--  <li class="has-dropdown vertical-menu-link"><a href="https://brasil.pregel2.com/services">Services</a> -->
    <ul class="level0 dropdown arrow-box">
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/servicos/ciencia-dos-alimentos-e-servicos-tecnicos/">Ciência dos Alimentos e Serviços Técnicos</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/servicos/marca-personalizada/">Marca Personalizada</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/servicos/perguntas-frequentes/">Perguntas Frequentes</a></li>
      <li class="level1 menu-item"><a href="https://brasil.pregel2.com/servicos/servico-ao-cliente/">Serviço ao Cliente</a></li>
    </ul>
  </li>

  <li>
    <a href="https://brasil.pregel2.com/contato">Contato</a>
  </li>

</ul>

</section>
</nav>